#!/bin/bash

DIRS=$(find * -maxdepth 0 -type d)

PYTHON=$(which python)

for DIR in $DIRS; do
    cd $DIR

    if [[ $* == *--uninstall* ]]; then
        echo "UNINSTALLING $DIR"
        $($PYTHON setup.py develop)
    fi

    cd ..
done
