#!/bin/bash

cd libs
DIRS=$(find * -maxdepth 0 -type d)

PYTHON=$(which python)

for DIR in $DIRS; do
    cd $DIR

    if [[ $* == *--uninstall* ]]; then
        echo "UNINSTALLING $DIR"
        $($PYTHON -m pip uninstall .)
    fi

    if [[ $* != *--uninstall* ]]; then
        echo "INSTALLING $DIR..."
        $($PYTHON -m pip install .)
    fi

    cd ..
done
